export const POKEMONS_LOADING = 'POKEMONS_LOADING';
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';
export const GET_POKEMONS_FAILURE = 'GET_POKEMONS_FAILURE';
export const POKEMON_LOADING = 'POKEMON_LOADING';
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMON_FAILURE = 'GET_POKEMON_FAILURE';
export const INCREASE_PAGE_COUNT = 'INCREASE_PAGE_COUNT';
export const CATCH_POKEMON = 'CATCH_POKEMON';
